### ISSUE TITLE
Make the tier scroll down with weapons

### ISSUE THREAD

**Issue by kmonte** [weblue/wanna_b_tierlist#47]
I want to be able to see what tier a weapon is when I ctrl + f for it

**Comment by malsf21** [comment]
I'll see if I can handle this. Not gonna lie, I have no idea how I would do this (probably by adding some sort of ID on the tier separators and then running some sort of JS function that gave that specific element a higher z-index or position fixed/sticky). @weblue any thoughts?

**Comment by kmonte** [comment]
Not to backseat program, but iirc you're using angular, so could you do something with this? 
https://medium.com/@EliaPalme/angular2-sticky-header-scroll-then-fix-ab4c54fada1f

**Comment by weblue** [comment]
We're using AngularJS, not the newer Angular, so we have to figure out a Bootstrap or CSS implementation

**Comment by malsf21** [comment]
It's a good suggestion though, and the CSS behind it (i.e. [this article the writer cites](https://css-tricks.com/scroll-fix-content/)) might be usable. I just wonder if it'll be super messy, and if there's maybe an easier way to do this by restructuring how the table displays the tiers.

**Comment by wastestime** [comment]
W3 also provides a good basis [here](https://www.w3schools.com/howto/howto_js_sticky_header.asp) on a minimal example. @malsf21 There probably is an easier way if you decide to separate the tables from each tier apart.

**Comment by malsf21** [comment]
We're in the process of reworking the entire project with Angular 2, and I think we'll have it implemented by then. The roadblock with a simple sticky header is the already existing fixed navbar, though we'll figure something out.

**Comment by weblue** [comment]
Sorry to say that this most likely won't be implemented due to technical limitations

A significant amount of effort was put into attempting to format the subheaders in angular, however it seems that Angular refuses to play nice with "subheaders" (which are actually just custom data types injected into the weapon lists)

Because the subheaders are custom, we aren't able to apply the same approach as the linked medium article. For now this issue will be closed.

@malsf21 if you feel like taking a look later, feel free to reopen the issue
