### ISSUE TITLE
Why is there such a large differential between Dread and Paris Prime?

### ISSUE THREAD

**Issue by PKBeam** [weblue/wanna_b_tierlist#51]
There are two practical differences between these two bows:

- Paris Prime does substantially more damage on a charged shot (260 vs 200).
- Dread has a higher critical chance (50% vs. 45% at base, which scales to 125% vs. 112.5% with maxed Point Strike).

These two differences mitigate each other to a certain extent, so I don't see why there is such a massive gap between the two weapons. 

"Consistency" doesn't seem to be properly defined here, but "poor consistency" is noted under the Paris Prime and not the Dread. There does not seem to be a difference between the bows that could reasonably account for this.

Additionally, a status build would be equally viable on either bow. In fact, Hunter Munitions would benefit the Dread slightly more than the Paris Prime due to crit chance. Why is the Paris Prime listed as a status weapon but not Dread?

**Comment by nicomarg** [comment]
As I see it, the main difference is the fact that Paris Prime's main damage type is puncture (80%) while Dread does mostly slash damage (90%). This has two implications:

- Dread will have its native status procs adding with hunter munitions ones, which brings the chance to proc one slash status from 30% to 49.1% with the builds shown on the tier list. (There's even a chance to proc 2 slashes on one arrow) This is what is referred to as 'consistency' as the paris prime can pull the damage out, but you would have to be very lucky with hunter munitions.
- This allows more flexibility in the dread build, as you don't have to go vigilante armaments, a sub-optimal mod regarding DPS, but needed to get these hunter munitions procs. This allows to go for bladed rounds (or even argon scope if you own it), which boosts the DPS a lot. (another difference in the builds is the choice of not putting too much viral dmg on the dread build to increase the ratio of slash procs over viral)

As to why these slash procs matter so badly, it's because slash DoTs bypass armor and shields, and are one of the few means of damaging end-game enemies (along with a weapon proc'ing loads of corrosive status). No matter how high your dmg output is, a lvl 120 heavy gunner has 97.5% dmg reduction (or 91.5% using corrosive damage), so you won't kill it without bypassing this armor somehow.
So, slow weapons like paris and dread that can't proc 10-15 corrosive status on each enemy have to rely on slash.

Where you have a point is that the dread is also built for Crit/Status, even the linked build is a Crit/Status build, this could be updated, but is a minor mistake, and isn't influencing ranking.

**Comment by malsf21** [comment]
Going to close this since it's stale.
