### ISSUE TITLE
Frame Builds need to be added to rank them

### ISSUE THREAD

**Issue by weblue** [weblue/wanna_b_tierlist#6]
Frames are currently ranked by general potential in each category
Frames will be categorized by builds and ranked

**Comment by weblue** [comment]
On hold while waiting for Kalgash to finish his cheatsheet in 2018

**Comment by wastestime** [comment]
@sakai4eva seeing as how [this variation of Kalgash's tier list](https://docs.google.com/spreadsheets/d/1LARmEzgHrZx8-ijkoKulgeE7f4ACE4XM0HB08ZlQs_k/edit#gid=31469109) is the latest (into 2019 at this point) what are the plans for ranking the warframes in this tier list?

**Comment by sakai4eva** [comment]
Please forgive the lack of attention being paid into warframes. It is a multi-faceted challenge with the following roadblocks: 

1. There is a difficulty in classification of frames. 

Each frame has role/capability overlaps and divergence to the point where judging their capability in performing such role/capability is difficult and non-objective. This is opposed to weapons where the unity of purpose (weapons = kill) vs multi-faceted capabilities of frames makes it hard to perform quick and repeatable tests. 

2. Testing regime is impossible to set. 

Based on the above, testing how a frame is easy to use, in other words the handling of it is too subjective. While on weapons I can stand my ground as a curator with rigorous testing regime to back my position, I can hardly do the same with frames. 

3. Opinion bias is too strong to use a semi-objective ranking system. 

This is, largely, the biggest hurdle to get past. Personally, there are frames that I personally "prefer" when dealing with certain situations vs. what could have been done in other ways. For example, when solo-ing Interceptions, Noise Arrow-based Ivara is presumed to be a much better alternative than, say, Banish-based Limbo or Slow-based Nova but due to my personal preference I would prefer to use the latter two than Ivara. Also, anecdotally, most of reddit would consider Mesa to be a "glass cannon" frame when her abilities would actually give her 90% damage reduction. 


All of the above factors make it really hard to make an objective tier list without a great degree of collaboration, and hence the delays until this point.
